from hcsvlab_robochef.rdf.namespaces import *


NAMEMAP = {
             'ambig-paragraph': ICEA.ambigparagraph,
             'bold': ICEA.bold,
             'byline': ICEA.byline,
             'changed': ICEA.changed,
             'corpus': ICEA.corpus,
             'correction': ARTA.correction,
             'deleted': ICEA.deleted,
             'discontinuous': ICEA.discontinuous,
             'dubious-nonsense': CA.dubious_nonsense,
             'editorial': ICEA.editorial,
             'ellipsis': COOEEA.ellipsis,
             'elongation': CA.elongation,
             'extended list': ACEA.extended_list,
             'extratext': ICEA.extratext,
             'footnote': ICEA.footnote,
             'footnote-ref': ICEA.footnoteref,
             'foreign': ICEA.foreign,
             'format': ICEA['format'],
             'heading': ICEA.heading,
             'incomplete': ICEA.incomplete,
             'inserted': ICEA.inserted,
             'interjection': ARTA.interjection,
             'intonation': CA.intonation,
             'italic': ICEA.italic,
             'latched-utterance': CA.latched_utterance,
             'laughter': MONASHA.laughter,
             'linebreak': ICEA.linebreak,
             'list': ICEA.list,
             'longdash': ICEA.longdash,
             'longpause': ICEA.longpause,
             'marginalia': ICEA.marginalia,
             'medpause': ICEA.medpause,
             'mention': ICEA.mention,
             'micropause': CA.micropause,
             'misc': ACEA.misc,
             'normalised-discontinuous': ICEA.normalised_discontinuous,
             'normative-deletion': ICEA.normative_deletion,
             'normative-insertion': ICEA.normative_insertion,
             'normative-replacement': ICEA.normative_replacement,
             'note': ACEA.note,
             'original-normalisation': ICEA.original_normalisation,
             'overlap': MONASHA.overlap,
             'overlapset': ICEA.overlapset,
             'pageno': COOEEA.pageno,
             'paragraph': ICEA.paragraph,
             'pause': ICEA.pause,
             'quote': ICEA.quote,
             'redacted': MONASHA.redacted,
             'roman': ICEA.roman,
             'sent': ICEA.sent,
             'signature': ICEA.signature,
             'smallcaps': ICEA.smallcaps,
             'space': ICEA.space,
             'speaker': ICEA.speaker,
             'special character': ACEA.special_character,
             'speed': CA.speed,
             'subheading': ICEA.subheading,
             'subscript': ICEA.subscript,
             'subtext': ICEA.subtext,
             'superscript': ICEA.superscript,
             'text': ICEA.text,
             'typeface': ICEA.typeface,
             'uncertain': ICEA.uncertain,
             'underline': ICEA.underline,
             'unknown': CA.unknown,
             'untranscribed': ICEA.untranscribed,
             'unuseable-char': ICEA.unuseable_char,
             'volume': CA.volume,
             'word': ICEA.word,
             'MAU' : MAUS.phonetic,
             'KAN' : MAUS.canonical,
             'ORT' : MAUS.orthography,
             
 }